spring:
  profiles:
    active: local
  h2.console:
    enabled: true
    path: '/console'

  main:
    banner-mode: off

management:
  endpoints:
    web:
      base-path: '/status'
  metrics:
    enable:
      http: false
